config/routes.rb
Rails.application.routes.draw do
  root "fines#index"
  resources :car_models
  resources :car_types
  resources :companies
  resources :fine_points

  resources :cars do
    post :enable_disable
  end
  resources :fines do
    post :identified_unidentified
  end
  resources :users do
    post :enable_disable
  end

  devise_for :users, path: ''
  # path: '' => nao deixa dar conflito de rotas no devise
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :user
  belongs_to :branch, class_name: "Company", foreign_key: :branch_id
  belongs_to :detran, class_name: "State", foreign_key: :detran_id
  belongs_to :fine_point
  belongs_to :company
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

  enum fine_status: [:identified, :unidentified]
  
  validates :fine_number, presence: true, uniqueness: true
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController
  before_action :fill_fields, only: %i[new create edit update]
  before_action :getfine_points, only: %i[new create edit update]
  before_action :getstates, only: %i[new create edit]
  before_action :set_fine, only: %i[show edit update destroy]
  before_action :set_fine_status, only: :identified_unidentified

  # GET /fines or /fines.json
  def index
    @fines = Fine.all.paginate(page: params[:page], per_page: 2)
  end

  # GET /fines/1 or /fines/1.json
  def show; end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit; end

  # POST /fines or /fines.json
  def create
    @fine = Fine.new(fine_params)
    @fine.company = current_company
    @fine.created_by = current_user
    respond_to do |format|
      if @fine.save
        format.html { redirect_to fine_url(@fine), notice: created_msg }
        format.json { render :show, status: :created, location: @fine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
    #   rescue
    #     redirect_to new_fine_url, alert: I18n.t("errors.rescue.fields"), class: 'alert'
  end

  # PATCH/PUT /fines/1 or /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to fine_url(@fine), notice: updated_msg }
        format.json { render :show, status: :ok, location: @fine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  rescue StandardError
    redirect_to edit_fine_url, alert: I18n.t('errors.rescue.fields'), class: 'alert'
  end

  # DELETE /fines/1 or /fines/1.json
  def destroy
    @fine.destroy

    respond_to do |format|
      format.html { redirect_to fines_url, notice: destroyed_msg }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fine
    @fine = Fine.find(params[:id])
  end

  def getstates
    @states = State.all # State.where(acronym: ["SC", "PR"])
  end

  def getfine_points
    @fine_points = FinePoint.all
  end

  def set_fine_status
    @fine = Fine.find(params[:fine_id])
  end

  def fill_fields
    @users = User.all
    @branches = Company.all
    # @branches = Company.where(company_type: :branch)
  end

  # Only allow a list of trusted parameters through.
  def fine_params
    params.require(:fine).permit(:user_id, :fine_date, :fine_status, :fine_number, :branch_id, :company_type,
                                 :detran_id, :fine_point_id)
  end
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/views/fines/_form.html.erb
<div class="flex">
<%= form_with(model: fine, local: true) do |form| %>
  <% if fine.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% fine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, options_from_collection_for_select(@users, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :fine_date %>
    <%= form.datetime_field :fine_date %>
  </div>

  <div class="field">
    <%= form.label :fine_status %>
    <p><%= form.select :fine_status, options_for_enum(:fine_statuses) %></p>
  </div>

  <div class="field">
    <%= form.label :fine_number %>
    <%= form.text_field :fine_number %>
  </div>


  <div class="field">
    <%= form.label t("activerecord.attributes.fine.detran_id") %>
    <%= form.select :detran_id, options_from_collection_for_select(@states, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label t("activerecord.attributes.company_types.branch") %>
    <%= form.select :branch_id, options_from_collection_for_select(@branches, :id, :name) %>
  </div><br>

  <div class="field">
    <%= form.label t("activerecord.attributes.fine_point.name") %>
    <%= form.select :fine_point_id, options_from_collection_for_select(@fine_points, :id, :name) %>
  </div>

    <div class="field">
    <%= form.label t("activerecord.attributes.fine_point.point") %>
    <%= form.select :fine_point_id, options_from_collection_for_select(@fine_points, :id, :point) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/fines/edit.html.erb
<h1><%= editing_model %></h1>

<%= render 'form', fine: @fine %>

<%= link_to t("general.show"), @fine %>
<%= link_to t("general.back"), fines_path %>

app/views/fines/index.html.erb
<div class="d-flex flex-col">
  <h1 class="left"><%= t("general.fines") %></h1>
</div> <hr>
<div class="mb-10 d-flex justify-between align-items-center">
  <p class="second-color h6"><%= t'general.show' %> <span class="opacity-50"><%= @fines.count %></span></p>
  <%= link_to new_fine_path do %>
    <button type="button" class="mb-10 btn btn-default supremo-btn-gray text-light"><%= link_to new_model_f, new_fine_path, class: "text-white" %></button>
<% end %>
</div>

<table class="table">
  <thead>
    <tr class="jumbotron">
      <th class="semi-bold"><%= t('general.conductor').upcase %></th>
      <th><%= t('table.date').upcase %></th>
      <th><%= t("table.fine_point").upcase %></th>
      <th><%= t('table.status').upcase %></th>
      <th><%= t('table.fine_number').upcase %></th>
      <th><%= t('activerecord.attributes.fine.detran_id').upcase %></th>
      <th><%= t("activerecord.models.company").upcase %></th>
      <th colspan="5" class="text-center"><%= t("general.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fines.each do |f| %>
    <tr>
        <%= link_to "" do %>
          <td title="Visualizar multa de <%= (f.user&.name).capitalize %>">
          <%= link_to "#{truncate((f.user&.name).capitalize, length: 16)}", fine_path(f), class: "semi-bold" %>
        </td>

        <td><%= l(f.fine_date, format: :short) %></td>
        <td><%= f.fine_point&.name %></td>
        <td><%= enum_to_name(f, :fine_status) %></td>
        <td><%= f.fine_number %></td>
        <td><%= f.detran&.acronym %></td>
        <td><%= f.branch&.name %></td>
        <% end %>
        <td>
          <div class="dropdown text-center">
            <button type="button" class="fas fa-ellipsis-v supremo-hover-click" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to t('general.show'), f %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "status", fine_identified_unidentified_path(f), method: :post, remote: true %></li>
              <li><%= link_to t('general.delete'), fine_path(f), method: :delete, data: { confirm: t("general.messages.confirm") } %></li>
            </ul>&#160; &#160;
            <%= link_to fa_icon('user-edit'), edit_user_path(f), class: "pad-left-5" if current_user.admin? || current_user.manager? %>
          </div>
        </td>
  <% end %>
  </tbody>
</table>

<% if params[:page].to_i != nil && params[:page].to_i <= 1 %>
  <div class="d-flex justify-between">
    <span class="opacity-50 h5"><%= records %></span>
    <div class="supremo_pagination right">
      <%= will_paginate @fines, previous_label: fa_icon('angle-left'), next_label: fa_icon('angle-right') %>
    </div>
  </div>
  <% else %>
  <div class="supremo_pagination right">
    <%= will_paginate @fines, previous_label: fa_icon('angle-left'), next_label: fa_icon('angle-right') %>
  </div>
<% end %>

app/views/fines/new.html.erb
<h1><%= new_model %></h1>

<%= render 'form', fine: @fine %>

<%= link_to t("general.back"), fines_path %>

app/views/fines/show.html.erb
<p>
  <strong><%= t("general.name") %>:</strong>
  <%= @fine.user.name.capitalize %>
</p>

<p>
  <strong><%= t("activerecord.attributes.fine.fine_date") %>:</strong>
  <%= @fine.fine_date %>
</p>

<p>
  <strong><%= t("activerecord.attributes.fine.fine_status") %>:</strong>
  <%= enum_to_name(@fine, :fine_status) %>
</p>

<p>
  <strong><%= t("activerecord.attributes.fine.fine_number") %>:</strong>
  <%= @fine.fine_number %>
</p>

<p>
  <strong>PONTOS DA MULTA:</strong>
  <%= @fine.fine_point&.name %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.company_type") %>:</strong>
  <%= @fine.branch&.name %>
</p>

<%= link_to t("general.edit"), edit_fine_path(@fine) %>
<%= link_to t("general.back"), fines_path %>