config/routes.rb
Rails.application.routes.draw do
  root "fines#index"
  resources :car_models
  resources :car_types
  resources :companies
  resources :fine_points

  resources :cars do
    post :enable_disable
  end
  resources :fines do
    post :identified_unidentified
  end
  resources :users do
    post :enable_disable
  end

  devise_for :users, path: ''
  # path: '' => nao deixa dar conflito de rotas no devise
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :city
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

=begin
  has_many :cars
  has_many :car_brands
  has_many :car_models
  has_many :car_types
  has_many :fines
  has_many :fine_points
  has_many :users
=end

  has_many :branches, class_name: "Company", foreign_key: :company_type

  enum company_type: [:main, :branch]

  validates :name, presence: true, uniqueness: true
  validates :cnpj, :phone, :zipcode, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  before_action :get_city, only: [:new, :edit]
  # GET /companies or /companies.json
  def index
    @companies = Company.all.paginate(page: params[:page], per_page: 2)
  end
  def new
    @company = Company.new
  end
  def show; end
  def edit; end

  def create
    @company = Company.new(company_params)
    @company.company = current_company
    @company.created_by = current_user

    respond_to do |format|
      if @company.save
        format.html { redirect_to company_url(@company), notice: created_msg }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
=begin
  rescue
    redirect_to new_company_url, alert: I18n.t("errors.rescue.fields"), class: 'alert'
=end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to company_url(@company), notice: updated_msg }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  rescue
    redirect_to edit_company_url, alert: I18n.t("errors.rescue.fields"), class: 'alert'
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url, notice: destroyed_msg }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

=begin
  def set_city
    state = State.select(:id).where(acronym: ["SC", "PR"])
    @cities = City.where(state_id: state)
    @states = State.where(acronym: ["SC","PR"])
  end
=end

    def get_city
      @states = State.where(acronym: ["SC", "PR"])
      state = State.select(:id).where(acronym: ["SC", "PR"])

      @cities = City.where(state_id: state)
    end
    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :company_type, :cnpj, :phone, :address, :number, :zipcode, :district, :city_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>
      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label t("activerecord.attributes.company.company_type") %>
    <%= form.select :company_type, options_for_enum(:company_types) %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, options_from_collection_for_select(@states, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.select :city_id, options_from_collection_for_select(@cities, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1><%= editing_model %></h1>

<%= render 'form', company: @company %>

<%= link_to t('general.show'), @company %>
<%= link_to t("general.back"), companies_path %>

app/views/companies/index.html.erb
<div class="d-flex flex-col">
  <h1 class="left"><%= t("activerecord.models.company") %></h1>
</div> <hr>
<div class="mb-10 d-flex justify-between align-items-center">
  <p class="second-color h6"><%= t'general.show' %> <span class="opacity-50"><%= @companies.count %></span></p>
  <%= link_to new_company_path do %>
    <button type="button" class="mb-10 btn btn-default supremo-btn-gray text-light"><%= new_model_f %></button>
  <% end %>
</div>

<table class="table">
  <thead>
    <tr class="jumbotron">
      <th><%= t("activerecord.attributes.company.name") %></th>
      <th><%= t("activerecord.attributes.company.company_type") %></th>
      <th><%= t("activerecord.attributes.company.cnpj") %></th>
      <th><%= t("activerecord.attributes.company.phone") %></th>
      <th><%= t("activerecord.attributes.company.address") %></th>
      <th><%= t("activerecord.attributes.company.number") %></th>
      <th><%= t("activerecord.attributes.company.zipcode") %></th>
      <th><%= t("activerecord.attributes.company.district") %></th>
      <th><%= t("activerecord.attributes.company.city_id") %></th>
      <th><%= t("activerecord.models.state") %></th>
      <th colspan="3" class="text-center"><%= t("general.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td class="semi-bold"><%= truncate(company.name, length: 10) %></td>
        <td><%= enum_to_name(company, :company_type) %></td>
        <td><%= truncate(company.cnpj, length: 10) %></td>
        <td><%= truncate(company.phone, length: 10) %></td>
        <td><%= truncate(company.address, length: 10) %></td>
        <td><%= company.number %></td>
        <td><%= truncate(company.zipcode, length: 6) %></td>
        <td><%= truncate(company.district, length: 10) %></td>
        <td><%= company.city&.name %></td>
        <td><%= company.city&.state&.acronym %></td>

        <% if current_user.root? %>
          <td>
            <div class="dropdown text-center">
              <button type="button" class="fas fa-ellipsis-v supremo-hover-click" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><%= link_to t("general.show"), company_path(company) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to t("general.delete"), company_path(company), method: :delete, data: {confirm: I18n.t("general.messages.confirm")} %></li>
              </ul>&#160 &#160
              <%= link_to fa_icon('user-edit'), edit_company_path(company), class: "pad-left-5" %>
            </div>
          </td>
        <% else %>
          <td class="text-center"><li><%= link_to t("general.show"), company_path(company) %></li></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if params[:page].to_i != nil && params[:page].to_i <= 1 %>
  <div class="d-flex justify-between">
    <span class="opacity-50 h5"><%= records %></span>
    <div class="supremo_pagination right">
      <%= will_paginate @companies, previous_label: fa_icon('angle-left'), next_label: fa_icon('angle-right') %>
    </div>
  </div>
<% else %>
  <div class="supremo_pagination right">
    <%= will_paginate @companies, previous_label: fa_icon('angle-left'), next_label: fa_icon('angle-right') %>
  </div>
<% end %>

app/views/companies/new.html.erb
<h1><%= new_model %></h1>

<%= render 'form', company: @company %>

<%= link_to t("general.back"), companies_path %>

app/views/companies/show.html.erb
<p>
  <strong><%= t("activerecord.attributes.company.name") %>:</strong>
  <%= @company.name %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.company_type") %>:</strong>
  <%= @company.company_type %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.cnpj") %>:</strong>
  <%= @company.cnpj %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.phone") %>:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.address") %>:</strong>
  <%= @company.address %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.number") %>:</strong>
  <%= @company.number %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.zipcode") %>:</strong>
  <%= @company.zipcode %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.district") %>:</strong>
  <%= @company.district %>
</p>

<p>
  <strong><%= t("activerecord.attributes.company.city_id") %>:</strong>
  <%= @company.city.name %>
</p>

<%= link_to t("general.edit"), edit_company_path(@company) %>
<%= link_to t("general.back"), companies_path %>