config/routes.rb
Rails.application.routes.draw do
  root "fines#index"
  resources :car_models
  resources :car_types
  resources :companies
  resources :fine_points

  resources :cars do
    post :enable_disable
  end
  resources :fines do
    post :identified_unidentified
  end
  resources :users do
    post :enable_disable
  end

  devise_for :users, path: ''
  # path: '' => nao deixa dar conflito de rotas no devise
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :car_model
  belongs_to :company
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

  enum status: [:enabled, :disabled]

  validates :license_plate, uniqueness: true
end

app/models/car_brand.rb
class CarBrand < ApplicationRecord
  belongs_to :company
  belongs_to :created_by, class_name: "User", foreign_key: :created_by
  has_many :car_models

  validates :name, presence: true
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :car_brand
  belongs_to :car_type
  belongs_to :company
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

  has_many :cars

  validates :name, presence: true
end

app/models/car_type.rb
class CarType < ApplicationRecord
  belongs_to :company
  belongs_to :created_by, class_name: "User" , foreign_key: :created_by
  has_many :car_models

  validates :name, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  # validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :city
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

=begin
  has_many :cars
  has_many :car_brands
  has_many :car_models
  has_many :car_types
  has_many :fines
  has_many :fine_points
  has_many :users
=end

  has_many :branches, class_name: "Company", foreign_key: :company_type

  enum company_type: [:main, :branch]

  validates :name, presence: true, uniqueness: true
  validates :cnpj, :phone, :zipcode, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states

  # validates :name, presence: true
end

app/models/fine.rb
class Fine < ApplicationRecord
  belongs_to :user
  belongs_to :branch, class_name: "Company", foreign_key: :branch_id
  belongs_to :detran, class_name: "State", foreign_key: :detran_id
  belongs_to :fine_point
  belongs_to :company
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

  enum fine_status: [:identified, :unidentified]
  
  validates :fine_number, presence: true, uniqueness: true
end

app/models/fine_point.rb
class FinePoint < ApplicationRecord
  belongs_to :company
  belongs_to :created_by, class_name: "User", foreign_key: :created_by

  # validates :name, presence: true, uniqueness: true
  # validates :point, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  has_many :cities
  has_many :detrans

  # validates :acronym, presence: true
end

app/models/translate.rb
class Translate
  def self.created_msg controller_name = nil
    I18n.t("general.messages.created", model: I18n.t("activerecord.models.#{controller_name.underscore}"))
  end
  def self.destroyed_msg controller_name = nil
    I18n.t("general.messages.destroyed", model: I18n.t("activerecord.models.#{controller_name.underscore}"))
  end
  def self.registered_msg controller_name = nil
    I18n.t("general.messages.created", model: I18n.t("activerecord.models.#{controller_name.underscore}"))
  end
  def self.updated_msg controller_name = nil
    I18n.t("general.messages.updated", model: I18n.t("activerecord.models.#{controller_name.underscore}"))
  end


  # ------ errors ------
  # def self.register_error controller_name = nil
  # end
  # def self.edit_error controller_name = nil
  # end
  # def self.destroy_error controller_name = nil
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  #belongs_to :created_by, class_name: "User", foreign_key: :created_by

  enum status: [:enabled, :disabled]
  enum user_type: [:users, :admin, :manager]
  # validate :name, :status, user_types, presence: true

  def admin?
    self.user_type == "admin"
  end
  def manager?
    self.user_type == "manager"
  end
  def root?
    admin? || manager?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_company
    current_user.company
  end

  def options_for_enum enum_name
    model_name = controller_name.classify.constantize
    values = eval("#{model_name}.#{enum_name}")
    values.keys.map { |w| [t("activerecord.attributes.#{enum_name}.#{w}" ), w] }
  end

  def enum_to_name model, enum_name
    value = model.try(enum_name)
    t("activerecord.attributes.#{enum_name.to_s.pluralize}.#{value}") unless value.blank?
  end

  def editing_model
    model_name = controller_name.classify.underscore
    t("general.editing", model: t("activerecord.models.#{model_name}") )
  end
  def new_model
    model_name = controller_name.classify.underscore
    t("general.new_model", model: t("activerecord.models.#{model_name}") )
  end
  def new_model_f
    model_name = controller_name.classify.underscore
    t("general.new_model_f", model: t("activerecord.models.#{model_name}") )
  end

end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/car_types_helper.rb
module CarTypesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<nav class="flex-col">
  <%= link_to fa_icon('user', type: :regular, text: t("activerecord.models.user")), users_path %>
  <%= link_to fa_icon('file-alt', type: :regular, text: t("activerecord.models.fine")), fines_path %>
  <%= link_to fa_icon('file-powerpoint', type: :regular, text: t("activerecord.models.fine_point")), fine_points_path %>
  <%= link_to fa_icon('building', type: :regular, text: t("activerecord.models.company")), companies_path %>
  <%= link_to fa_icon('car', text: t("activerecord.models.car")), cars_path %>
  <%= link_to fa_icon('car-side', text: t("activerecord.models.car_type")), car_types_path %>
  <%= link_to fa_icon('car-side', text: t("activerecord.models.car_model")), car_models_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path("logo-ico.png") %>
    <title><%= t("general.supreme") %></title>
  </head>

  <body>
    <header style="margin-bottom:100px;" class="container-fluid supremo-bg-dark">
      <%= render 'shared/header' if signed_in? %>
    </header>
    <main class="container-fluid">
      <div>
        <div>
          <%= image_tag("cta-concreto1.png") unless signed_in? %>
          <!-- Responsive Nav -->
          <nav style="margin-top: 20px" class="hidden-xs hidden-sm mt-10 col-sm-2 col-md-3 col-lg-2 d-flex">
            <%= render "shared/nav_left" if signed_in? %>
          </nav>
          <nav class="hidden-md hidden-lg">
            <%= render "shared/nav_menu" if signed_in? %>
          </nav> <!-- Responsive Nav -->
        </div>

        <div class="col-xs-12 col-sm-12 col-md-9 col-lg-10 right">
          <div class="cotainer right col-5">
            <%= render 'shared/system_alerts' %>
          </div>
          <%= yield %>
        </div>

      </div>
    </main>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="container-fluid navbar-fixed-top supremo-bg-dark">
  <div class="container-fluid">

    <div class="d-flex justify-between">
      <a href="/"><%= image_tag ("logo-ico.png"), size:"48x41", class: 'mt-10' %></a>

      <ul>
        <li role="presentation" class="dropdown">

          <a class="dropdown-toggle text-white container-fluid" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <div class=" d-flex align-items-center">
              <span class="text-dark"><%= ("#{current_user&.name.split.first.downcase}") %> <span class="caret"></span></span>
              <span><%= fa_icon('user-circle 2x') %></span>
            </div>
          </a>

          <ul class="dropdown-menu no-hover">
            <li><%= link_to fa_icon('user-edit' , text: t("general.edit")), edit_user_path(current_user) %></li>
            <li><%= link_to fa_icon('sign-out-alt' , text: t("general.exit")), destroy_user_session_path, method: :delete %></li>
          </ul>

        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/shared/_nav_left.html.erb
<nav class="row">
  <ul class="nav nav-pills nav-stacked">
    <li class="<%= 'active' if params[:controller] == 'users' %>">
      <%= link_to fa_icon('user', type: :regular, text: t("activerecord.models.user")), users_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'fines' %>">
      <%= link_to fa_icon('file-alt', type: :regular, text: t("activerecord.models.fine")), fines_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'fine_points' %>">
      <%= link_to fa_icon('file-powerpoint', type: :regular, text: t("activerecord.models.fine_point")), fine_points_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'companies' %>">
      <%= link_to fa_icon('building', type: :regular, text: t("activerecord.models.company")), companies_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'cars' %>">
      <%= link_to fa_icon('car', text: t("activerecord.models.car")), cars_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'car_types' %>">
      <%= link_to fa_icon('car-side', text: t("activerecord.models.car_type")), car_types_path %>
    </li>
    <li class="<%= 'active' if params[:controller] == 'car_models' %>">
      <%= link_to fa_icon('car-side', text: t("activerecord.models.car_model")), car_models_path %>
    </li>
  </ul>
</nav>

app/views/shared/_nav_menu.html.erb
<ul class="only-mobile nav navbar-nav nav-pills nav-stacked">
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle container-fluid" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      <button class="btn-default supremo-btn-gray text-light btn btn-dark">menu</button>
    </a>
    <ul class="dropdown-menu no-hover">
      <li class="<%= 'active' if params[:controller] == 'users' %>">
        <%= link_to fa_icon('user', type: :regular, text: t("activerecord.models.user")), users_path %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'fines' %>">
        <%= link_to fa_icon('file-alt', type: :regular, text: t("activerecord.models.fine")), fines_path %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'fine_points' %>">
        <%= link_to fa_icon('file-powerpoint', type: :regular, text: t("activerecord.models.fine_point")), fine_points_path %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'companies' %>">
        <%= link_to fa_icon('building', type: :regular, text: t("activerecord.models.company")), companies_path %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'cars' %>">
        <%= link_to fa_icon('car', text: t("activerecord.models.car")), cars_path %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'car_types' %>">
        <%= link_to fa_icon('car-side', text: t("activerecord.models.car_type")), car_types_path %>
      </li>
      <li class="<%= 'active' if params[:controller] == 'car_models' %>">
        <%= link_to fa_icon('car-side', text: t("activerecord.models.car_model")), car_models_path %>
      </li>
    </ul>
  </li>

</ul>

app/views/shared/_system_alerts.html.erb
<%
  alert_class = ""
  flash.each do |type, message|
    case type.to_s
    when "success"
      alert_class = "alert-success"
    when "error"
      alert_class = "alert-danger"
    when "alert"
      alert_class = "alert-warning"
    when "notice"
      alert_class = "alert-info"
    else
      alert_class = "alert-secondary"
    end
%>
  <div class="d-flex justify-between alert px-10 <%= alert_class %>">
    <%= message %>&#160; &#160;
    <%= link_to "<span>&times;<span>".html_safe, "data-dismiss": "alert", "aria-hidden": "true", class:"post hide" %>
  </div>
  <script type="text/javascript" charset="utf-8">
      $(".alert" ).fadeOut(6000);
  </script>
<% end %>